#cloud-config
package_upgrade: true
hostname: ${hostname}
fqdn: ${hostname}.${domain}
write_files:
#  - content: |
#      #!/bin/bash
#      # [w]ait [u]ntil [p]ort [i]s [a]ctually [o]pen
#      [ -n "$1" ] && \
#      while ! curl --output /dev/null --silent --head --fail http://$1; do sleep 2 && echo -n .; done;
#      exit $?
#    path: /opt/bin/wupiao
#    permissions: '0755'
  - content: |
      #!/bin/bash
      HOSTIP=`/usr/bin/curl -s http://169.254.169.254/latest/meta-data/local-ipv4`
      MLD=$$(echo ${domain} | cut -d"." -f1)
      TLD=$$(echo ${domain} | cut -d"." -f2)

      # Disable resolv.conf management by dhclient
      sed -i -e '/PEERDNS=/ s/=.*/=\"no\"/' /etc/sysconfig/network-scripts/ifcfg-eth0

      cat > /etc/sysconfig/network <<EOF
      NETWORKING=yes
      NOZEROCONF=yes
      DNS1=$${HOSTIP}
      SEARCH=${domain} node.consul
      EOF

      cat >/etc/hosts <<EOF
      $${HOSTIP} ${hostname}.${domain} ${hostname}
      127.0.0.1 localhost
      EOF

      echo "My hostname is: ${hostname}.${domain}, IP: $${HOSTIP}"
      echo "ambari-server has address: ${ambari_server}
    path: /var/lib/cloud/scripts/per-boot/setup_dns.sh
    owner: root:root
    permissions: 0755
